[project]
name = "crawling"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "hahahellooo", email = "hahahello777@gmail.com"},
]
dependencies = [
    "selenium>=4.27.1",
    "webdriver-manager>=4.0.2",
    "bs4>=0.0.2",
    "kafka>=1.3.5",
    "kafka-python>=2.0.2",
    "apache-airflow>=2.10.3",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
